#version 460


layout(local_size_x = 32, local_size_y = 32) in;

layout(push_constant) uniform params
{
  uvec2 res;
  mat4 proj;
} pushConstant;


layout(binding = 0, r32f) uniform image2D ssaoTex;
layout(binding = 1) uniform sampler2D depthTex;



void main() {
  ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

  if (fragCoord.x >= pushConstant.res.x || fragCoord.y >= pushConstant.res.y)
    return;

  vec2 uv = vec2(fragCoord * 2) / vec2(pushConstant.res) - 1.0f;


}